ProjectDiffChecker/config/routes.rb
Rails.application.routes.draw do
 

  get 'resumes/dene'

  resources :resumes, only: [:index, :new, :create, :destroy]
  root "resumes#index"

  resources :users do
   collection do
     get 'another_new'
     post 'another_create'
   end
  end

end

ProjectDiffChecker/app/models/resume.rb
class Resume < ActiveRecord::Base
	mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   validates :name, presence: true # Make sure the owner's name is present.
  
end

ProjectDiffChecker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ProjectDiffChecker/app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
   def index
      if params && params[:req]
         render :js => "window.location = '#{resumes_dene_path}'"
      end
      @resumes = Resume.all
   end
   
   def new
     @resume = Resume.new
   end
   
  
   def create
      @resume = Resume.new(resume_params)
      #raise @resume.inspect
      if @resume.save
         redirect_to resumes_path, notice: "The project #{@resume.name} has been uploaded."
         unzip_file(params[:resume][:attachment].tempfile, "C:/Users/buse/Desktop/oldu/")

      else
         render 'new'
      end
      
   end
   
   def destroy
      @resume = Resume.find(params[:id])
      @resume.destroy
      redirect_to resumes_path, notice:  "The project #{@resume.name} has been deleted."
     # redirect_to post_url(@post), status: :dene

   end

   private
      def resume_params
      params.require(:resume).permit(:name, :attachment)
   end

   def unzip_file(file_path,destination_path)
      Zip::ZipFile.open(file_path) { |zip_file|
        zip_file.each { |f|
          f_path=File.join(destination_path, f.name)
          FileUtils.mkdir_p(File.dirname(f_path))
          zip_file.extract(f, f_path) unless File.exist?(f_path)
        }
      }

    def dir_entries(source_path)
      files = Dir["C:/Users/buse/Desktop/oldu/"]
      puts files
    end

    end

    def dene
    end


   end

ProjectDiffChecker/app/helpers/application_helper.rb
module ApplicationHelper
end

ProjectDiffChecker/app/helpers/resumes_helper.rb
module ResumesHelper
end

ProjectDiffChecker/app/helpers/unzip_helper.rb
module UnzipHelper
end

ProjectDiffChecker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   
   <head>
      <title>Project Difference Checker</title>
       <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
   </head>
   
   <body>
      <div class = "container" style = "padding-top:20px;">
         <%= yield %>
      </div>
   </body>

</html>

ProjectDiffChecker/app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

ProjectDiffChecker/app/views/resumes/dene.html.erb
<div id="sol" style="background-color: gray;height:720; width: 99% float: left; margin-right: 9px; border: 1px solid black;">

	<div style="margin-right:1000px; background-color: red;">
	sol
	</div>
	<div style="margin-right: 500px; margin-left:130px;background-color: red;">
	sol
	</div>
	<div style="background-color: white; width: 500px; float: right; border: 1px solid red;">
	SAG
	</div>
	<div style="clear: right;"></div>	
</div>

ProjectDiffChecker/app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

ProjectDiffChecker/app/views/resumes/index.html.erb
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />

<%= link_to "New Project", new_resume_path, class: "btn btn-primary" %>

<br />
<br />

<table class = "table table-bordered table-striped">
   <thead>.
      <tr>
         <th>Name</th>
         <th>Download Link</th>
         <th> </th>
         <td> deneme check box<input class="accept_tos" id="tos" name="tos" type="checkbox" value="yes" /></td>
         <th><input type = "checkbox" id = "post_validate" name = "post[validated]" 
             value = "1" checked = "checked" />
               <input name = "post[validated]" type = "hidden" value = "0" /></th>

                 <select id="colors" multiple="multiple" name="colors[]"><option>Red</option>
                 <option>Green</option><option>Blue</option></select>
      </tr>
    </thead>
   
   <tbody>
      <% @resumes.each do |resume| %>
         <tr>
           
            <td><%= resume.name %></td>
            <td><%= link_to "Download Project", resume.attachment_url %></td>
            <td><%= button_to "Delete",  resume, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>

         </tr>
        
      <% end %>
   </tbody>
   
</table>

<script type="text/javascript">

$("#tos").click(function(e){

      e = e || window.event;
      e = e.target || e.srcElement;
      if (e.value == "yes"){
         console.log("GET");
          $.ajax({
           url:  "<%= resumes_path %>",
           data: {
             req: "dene"
           },
           success: function(data){
             console.log(data);
           }});
      }
   });
</script>

ProjectDiffChecker/app/views/resumes/new.html.erb
<% if !@resume.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @resume.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

<div class = "well">
   <%= form_for @resume, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>